In [1]:
import pandas as pd
import numpy as np
import ast
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings(action = 'ignore')

# USER ACTIVITY

In [2]:
df_userAct = pd.read_csv("UserActivity.csv")
df_userAct

User_ID         Title datetime time  datetime Year  \
0       ID_RT43AK77  comp_ID_IV5D      22:00:38              1   
1       ID_RT43AK77  comp_ID_IV5D      00:41:02              1   
2       ID_RT43AK77  comp_ID_IV5D      00:53:15              1   
3       ID_RT43AK77  comp_ID_IV5D      01:23:05              1   
4       ID_RT43AK77  comp_ID_IV5D      01:27:38              1   
...             ...           ...           ...            ...   
317287  ID_Z759BCS3   job_ID_5ONI      07:14:47              1   
317288  ID_WNJMADF8   job_ID_5ONI      06:24:46              1   
317289  ID_7NBY9MV2   job_ID_5ONI      11:56:35              1   
317290  ID_LHPJJSOK   job_ID_5ONI      01:27:13              1   
317291  ID_LCFNGARD   job_ID_5ONI      08:40:29              1   

        datetime Month  datetime Day_of_month  
0                   11                     22  
1                   11                     23  
2                   11                     23  
3                   11                     23  
4                   11                     23  
...                ...                    ...  
317287              11                     14  
317288              11                     14  
317289              11                     20  
317290              11                     14  
317291              11                     17  

[317292 rows x 6 columns]

In [3]:
df_userAct.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 317292 entries, 0 to 317291
Data columns (total 6 columns):
 #   Column                 Non-Null Count   Dtype 
---  ------                 --------------   ----- 
 0   User_ID                317292 non-null  object
 1   Title                  317292 non-null  object
 2   datetime time          317292 non-null  object
 3   datetime Year          317292 non-null  int64 
 4   datetime Month         317292 non-null  int64 
 5   datetime Day_of_month  317292 non-null  int64 
dtypes: int64(3), object(3)
memory usage: 14.5+ MB


In [4]:
len(pd.unique(df_userAct['User_ID']))

10400

In [5]:
len(pd.unique(df_userAct['datetime Year']))

1

In [6]:
df_userAct.drop('datetime Year', inplace=True, axis=1)

In [7]:
df_userAct["User_ID"] = df_userAct["User_ID"].astype("string")
df_userAct["datetime Month"] = df_userAct["datetime Month"].astype("string")

In [8]:
new = df_userAct["datetime Month"].copy()
df_userAct["User_ID"] = df_userAct["User_ID"].str.cat(new, sep ="_Month_")

In [9]:
df_userAct.drop('datetime Month', inplace=True, axis=1)

In [10]:
df_temp1 = df_userAct.groupby('User_ID').max() 

In [11]:
df_temp2 = df_userAct.groupby('User_ID').sum() 

In [12]:
df_temp3 = df_userAct.groupby('User_ID').count() 

In [13]:
df_temp = df_temp1

In [14]:
df_temp["datetime Day_of_month"] = df_temp1["datetime Day_of_month"]

In [15]:
df_temp["count_UA"] = df_temp3["datetime time"]

In [16]:
df_userAct = df_temp 

In [17]:
df_userAct.drop('Title', inplace=True, axis=1)

In [18]:
df_userAct

datetime time  datetime Day_of_month  count_UA
User_ID                                                            
ID_000H9XOP_Month_5       16:18:22                     26         6
ID_003YJHQA_Month_4       11:31:30                     12        11
ID_004UKSJV_Month_1       09:17:09                     15         1
ID_004UKSJV_Month_12      10:51:58                     29        11
ID_008D2J6C_Month_1       10:44:55                     15        10
...                            ...                    ...       ...
ID_ZZJKFBR5_Month_2       19:19:21                     20         2
ID_ZZMHNLNT_Month_4       11:57:10                      1         8
ID_ZZQK0LU6_Month_3       23:41:18                     30        67
ID_ZZUNZJ2U_Month_2       23:16:34                     30        12
ID_ZZVUJ45W_Month_3       09:32:57                      5        13

[15143 rows x 3 columns]

# DISCUSSIONS

In [19]:
df_disc = pd.read_csv("Discussion.csv")

In [20]:
df_disc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1439 entries, 0 to 1438
Data columns (total 9 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Competition ID           1439 non-null   object 
 1   Personal                 1439 non-null   int64  
 2   Theme                    159 non-null    float64
 3   Disc_ID                  1439 non-null   object 
 4   User_ID                  1439 non-null   object 
 5   Created At time          1439 non-null   object 
 6   Created At Year          1439 non-null   int64  
 7   Created At Month         1439 non-null   int64  
 8   Created At Day_of_month  1439 non-null   int64  
dtypes: float64(1), int64(4), object(4)
memory usage: 101.3+ KB


In [21]:
df_disc

Competition ID  Personal  Theme    Disc_ID      User_ID  \
0     GeneralDiscussion         1    NaN  ID_0BK7TH  ID_AAGFVLHH   
1     GeneralDiscussion         1    NaN  ID_ZFJ9J7  ID_0AJGQILU   
2     GeneralDiscussion         1    NaN  ID_ME45XX  ID_U90KK6KL   
3               ID_45W9         1    NaN  ID_2BG9IX  ID_U90KK6KL   
4     GeneralDiscussion         1    NaN  ID_251XVV  ID_F7HIGFHQ   
...                 ...       ...    ...        ...          ...   
1434  GeneralDiscussion         1    NaN  ID_09W0TZ  ID_AAJKI0P3   
1435  GeneralDiscussion         1    NaN  ID_613AUJ  ID_8A3X5IWU   
1436  GeneralDiscussion         1    NaN  ID_TCN8TB  ID_3NL0QLE6   
1437  GeneralDiscussion         1    NaN  ID_FTJ37Z  ID_3PL1LQQX   
1438  GeneralDiscussion         0    1.0  ID_ZOC5GY  ID_S4XIIL0Z   

      Created At time  Created At Year  Created At Month  \
0     19:48:26.862175                1                12   
1     09:37:52.039526                1                12   
2     17:50:33.894800                1                 2   
3     07:57:55.178845                1                 2   
4     19:56:13.041893                1                12   
...               ...              ...               ...   
1434  14:15:31.081484                1                 5   
1435  11:06:11.201934                1                 5   
1436  04:57:31.578153                1                 5   
1437  05:11:59.313759                1                 5   
1438  07:13:04.296241                1                 3   

      Created At Day_of_month  
0                          27  
1                          20  
2                           9  
3                          10  
4                          27  
...                       ...  
1434                       23  
1435                       14  
1436                       12  
1437                        9  
1438                       19  

[1439 rows x 9 columns]

In [22]:
len(pd.unique(df_disc['User_ID']))

1017

In [23]:
len(pd.unique(df_disc['Created At Year']))

1

In [24]:
df_disc["User_ID"] = df_disc["User_ID"].astype("string")
df_disc["Created At Month"] = df_disc["Created At Month"].astype("string")

In [25]:
new = df_disc["Created At Month"].copy()
df_disc["User_ID"] = df_disc["User_ID"].str.cat(new, sep ="_Month_")

In [26]:
pd.unique(df_disc['Theme'])

array([nan,  3.,  1.,  4.,  5.,  2.])

In [27]:
df_disc.rename(columns={'Created At time': 'Discussion_time'},  inplace = True)

In [28]:
df_disc.rename(columns={'Created At Year': 'Discussion_year'},  inplace = True)

In [29]:
df_disc.rename(columns={'Created At Month': 'Discussion_month'},  inplace = True)

In [30]:
df_disc.rename(columns={'Created At Day_of_month': 'Discussion_day'},  inplace = True)

In [31]:
df_disc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1439 entries, 0 to 1438
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Competition ID    1439 non-null   object 
 1   Personal          1439 non-null   int64  
 2   Theme             159 non-null    float64
 3   Disc_ID           1439 non-null   object 
 4   User_ID           1439 non-null   string 
 5   Discussion_time   1439 non-null   object 
 6   Discussion_year   1439 non-null   int64  
 7   Discussion_month  1439 non-null   string 
 8   Discussion_day    1439 non-null   int64  
dtypes: float64(1), int64(3), object(3), string(2)
memory usage: 101.3+ KB


# COMMENTS

In [32]:
df_com = pd.read_csv("Comments.csv")

In [33]:
df_com.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 467 entries, 0 to 466
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   Disc_ID                  467 non-null    object
 1   User_ID                  467 non-null    object
 2   Created At time          467 non-null    object
 3   Created At Year          467 non-null    int64 
 4   Created At Month         467 non-null    int64 
 5   Created At Day_of_month  467 non-null    int64 
dtypes: int64(3), object(3)
memory usage: 22.0+ KB


In [34]:
df_com

Disc_ID      User_ID  Created At time  Created At Year  \
0    ID_ONQEAR  ID_CEDNKSVV  16:18:44.841697                1   
1    ID_E0NHSS  ID_CEDNKSVV  17:30:40.566763                1   
2    ID_3XKIOF  ID_CEDNKSVV  13:28:47.950841                1   
3    ID_XCC6W4  ID_CEDNKSVV  18:42:17.362333                1   
4    ID_OIGXGK  ID_CEDNKSVV  18:57:54.540062                1   
..         ...          ...              ...              ...   
462  ID_DK2VV3  ID_GPXBD1BG  06:11:25.314720                1   
463  ID_5MJRT0  ID_2F218EUV  21:53:36.148890                1   
464  ID_RMQMJA  ID_9W2RXCMI  14:06:35.178439                1   
465  ID_V5431U  ID_RQEQ74SK  13:03:58.602412                1   
466  ID_V5431U  ID_7ICXZH0P  13:04:38.747046                1   

     Created At Month  Created At Day_of_month  
0                   5                       11  
1                  12                       23  
2                   1                        3  
3                   1                        5  
4                  12                       19  
..                ...                      ...  
462                 1                       14  
463                 1                       15  
464                 1                       23  
465                12                       29  
466                12                       29  

[467 rows x 6 columns]

In [35]:
len(pd.unique(df_com['User_ID']))

192

In [36]:
len(pd.unique(df_com['Created At Year']))

1

In [37]:
df_com.drop('Created At Year', inplace=True, axis=1)

In [38]:
df_com["User_ID"] = df_com["User_ID"].astype("string")
df_com["Created At Month"] = df_com["Created At Month"].astype("string")

In [39]:
new = df_com["Created At Month"].copy()
df_com["User_ID"] = df_com["User_ID"].str.cat(new, sep ="_Month_")

In [40]:
df_com.drop('Created At Month', inplace=True, axis=1)

In [41]:
df_com.rename(columns={'Created At time': 'comment_time'},  inplace = True)

In [42]:
df_com.rename(columns={'Created At Month': 'comment_month'},  inplace = True)

In [43]:
df_com.rename(columns={'Created At Day_of_month': 'comment_day'},  inplace = True)

In [44]:
df_com.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 467 entries, 0 to 466
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Disc_ID       467 non-null    object
 1   User_ID       467 non-null    string
 2   comment_time  467 non-null    object
 3   comment_day   467 non-null    int64 
dtypes: int64(1), object(2), string(1)
memory usage: 14.7+ KB


# MERGE 1

In [45]:
result1 = pd.merge(df_disc, df_com, how="outer", on=['User_ID', 'Disc_ID'])

In [46]:
result1

Competition ID  Personal  Theme    Disc_ID               User_ID  \
0     GeneralDiscussion       1.0    NaN  ID_0BK7TH  ID_AAGFVLHH_Month_12   
1     GeneralDiscussion       1.0    NaN  ID_ZFJ9J7  ID_0AJGQILU_Month_12   
2     GeneralDiscussion       1.0    NaN  ID_ME45XX   ID_U90KK6KL_Month_2   
3               ID_45W9       1.0    NaN  ID_2BG9IX   ID_U90KK6KL_Month_2   
4     GeneralDiscussion       1.0    NaN  ID_251XVV  ID_F7HIGFHQ_Month_12   
...                 ...       ...    ...        ...                   ...   
1848                NaN       NaN    NaN  ID_4R4V7V   ID_JKCAR4CP_Month_1   
1849                NaN       NaN    NaN  ID_ZGEWPJ   ID_LNXTXN3P_Month_1   
1850                NaN       NaN    NaN  ID_DK2VV3   ID_GPXBD1BG_Month_1   
1851                NaN       NaN    NaN  ID_RMQMJA   ID_9W2RXCMI_Month_1   
1852                NaN       NaN    NaN  ID_V5431U  ID_7ICXZH0P_Month_12   

      Discussion_time  Discussion_year Discussion_month  Discussion_day  \
0     19:48:26.862175              1.0               12            27.0   
1     09:37:52.039526              1.0               12            20.0   
2     17:50:33.894800              1.0                2             9.0   
3     07:57:55.178845              1.0                2            10.0   
4     19:56:13.041893              1.0               12            27.0   
...               ...              ...              ...             ...   
1848              NaN              NaN             <NA>             NaN   
1849              NaN              NaN             <NA>             NaN   
1850              NaN              NaN             <NA>             NaN   
1851              NaN              NaN             <NA>             NaN   
1852              NaN              NaN             <NA>             NaN   

         comment_time  comment_day  
0                 NaN          NaN  
1                 NaN          NaN  
2                 NaN          NaN  
3                 NaN          NaN  
4                 NaN          NaN  
...               ...          ...  
1848  13:40:41.651137         25.0  
1849  22:32:47.360368          5.0  
1850  06:11:25.314720         14.0  
1851  14:06:35.178439         23.0  
1852  13:04:38.747046         29.0  

[1853 rows x 11 columns]

In [47]:
result1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1853 entries, 0 to 1852
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Competition ID    1462 non-null   object 
 1   Personal          1462 non-null   float64
 2   Theme             178 non-null    float64
 3   Disc_ID           1853 non-null   object 
 4   User_ID           1853 non-null   string 
 5   Discussion_time   1462 non-null   object 
 6   Discussion_year   1462 non-null   float64
 7   Discussion_month  1462 non-null   string 
 8   Discussion_day    1462 non-null   float64
 9   comment_time      467 non-null    object 
 10  comment_day       467 non-null    float64
dtypes: float64(5), object(4), string(2)
memory usage: 173.7+ KB


# COMPETITIONS

In [48]:
df_comp = pd.read_csv("Competition.csv")

In [49]:
df_comp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 20 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   FeatureA                 247 non-null    object 
 1   FeatureB                 247 non-null    object 
 2   FeatureC                 196 non-null    float64
 3   FeatureD                 247 non-null    int64  
 4   FeatureE                 247 non-null    int64  
 5   SecretCode               247 non-null    int64  
 6   FeatureF                 247 non-null    object 
 7   FeatureG                 247 non-null    object 
 8   FeatureH                 247 non-null    object 
 9   FeatureI                 186 non-null    float64
 10  Country_ID               121 non-null    object 
 11  Comp_ID                  247 non-null    object 
 12  End Time time            224 non-null    object 
 13  End Time Year            224 non-null    float64
 14  End Time Month           2

In [50]:
df_comp

FeatureA FeatureB  FeatureC  FeatureD  FeatureE  SecretCode FeatureF  \
0     [2, 4]     [14]      15.0         0         2           1      [3]   
1        [1]       []       3.0         0         3           1      [1]   
2        [1]      [9]       2.0         0         2           1   [1, 5]   
3         []       []       1.0         0         2           1      [1]   
4         []      [6]       NaN         0         2           0       []   
..       ...      ...       ...       ...       ...         ...      ...   
242       []       []       NaN         1         2           0      [2]   
243      [1]       []       2.0         1         2           0      [1]   
244      [1]       []       NaN         0         2           1      [1]   
245      [1]       []      25.0         0         2           1      [1]   
246      [1]       []       2.0         0         2           0      [3]   

    FeatureG FeatureH  FeatureI Country_ID  Comp_ID End Time time  \
0         []       []       NaN       G3F0  ID_AU0T      21:05:00   
1         []      [1]       3.0       0Q35  ID_O21T      15:30:00   
2        [5]      [1]       2.0       EGI9  ID_W6XE      21:59:00   
3        [4]       []       NaN        NaN  ID_A2FN      12:00:00   
4        [4]      [2]       9.0        NaN  ID_X0PD      23:59:00   
..       ...      ...       ...        ...      ...           ...   
242      [5]      [2]       NaN        NaN  ID_GR92      15:00:00   
243      [5]      [1]       2.0        NaN  ID_8BH9      23:59:00   
244      [3]       []       NaN       H03V  ID_IHRZ      17:00:00   
245      [5]      [2]       NaN       EGI9  ID_CMWO      12:00:00   
246      [3]      [2]       2.0       ZEWU  ID_OAR6      23:59:00   

     End Time Year  End Time Month  End Time Day_of_month Start Time time  \
0              2.0             6.0                   19.0        07:00:00   
1              2.0             2.0                   15.0        12:00:00   
2              2.0             5.0                    9.0        08:00:00   
3              2.0             6.0                   22.0        12:00:00   
4              2.0             5.0                   31.0        09:00:00   
..             ...             ...                    ...             ...   
242            1.0             2.0                    1.0        05:00:00   
243            1.0             6.0                   27.0        15:00:00   
244            1.0            10.0                   20.0        08:57:00   
245            1.0             5.0                   31.0        12:00:00   
246            1.0             4.0                    4.0        11:00:00   

     Start Time Year  Start Time Month  Start Time Day_of_month  
0                  2                 6                       19  
1                  2                 2                        1  
2                  2                 3                       28  
3                  2                 6                       12  
4                  2                 5                       27  
..               ...               ...                      ...  
242                1                 1                        1  
243                1                 6                        1  
244                1                10                       19  
245                1                 5                        1  
246                1                 4                        2  

[247 rows x 20 columns]

In [51]:
len(pd.unique(df_comp['Comp_ID']))

247

In [52]:
len(pd.unique(df_comp['Start Time Year']))

5

# COMPETITION PARTICIPATION

In [53]:
df_compP = pd.read_csv("CompetitionPartipation.csv")

In [54]:
df_compP.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8385 entries, 0 to 8384
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   Competition ID               8385 non-null   object
 1   Participant Type             8385 non-null   int64 
 2   Successful Submission Count  1449 non-null   object
 3   User_ID                      8385 non-null   object
 4   Created At time              8385 non-null   object
 5   Created At Year              8385 non-null   int64 
 6   Created At Month             8385 non-null   int64 
 7   Created At Day_of_month      8385 non-null   int64 
dtypes: int64(4), object(4)
memory usage: 524.2+ KB


In [55]:
df_compP

Competition ID  Participant Type Successful Submission Count  \
0           ID_WPP3                 1                         NaN   
1           ID_ZN92                 1                         NaN   
2           ID_I9BN                 1                         NaN   
3           ID_PDKH                 1                    count 10   
4           ID_CFN7                 1                         NaN   
...             ...               ...                         ...   
8380        ID_F7QD                 1                         NaN   
8381        ID_F7QD                 1                         NaN   
8382        ID_F7QD                 1                         NaN   
8383        ID_F7QD                 1                         NaN   
8384        ID_F7QD                 1                         NaN   

          User_ID  Created At time  Created At Year  Created At Month  \
0     ID_40G01FGV  19:38:04.689865                1                11   
1     ID_40G01FGV  19:38:04.670583                1                11   
2     ID_40G01FGV  12:06:55.884320                1                12   
3     ID_40G01FGV  11:24:04.239058                1                12   
4     ID_P33ABQX5  05:16:09.052129                1                 5   
...           ...              ...              ...               ...   
8380  ID_QR2HEY6L  22:10:28.532519                1                 1   
8381  ID_K1MDGNKE  20:54:47.902303                1                 3   
8382  ID_M8FQBYIH  18:57:10.479540                1                12   
8383  ID_9IP2OICN  21:03:14.798218                1                12   
8384  ID_JUE09Z86  11:02:22.739630                1                 5   

      Created At Day_of_month  
0                          20  
1                          20  
2                          17  
3                           6  
4                          26  
...                       ...  
8380                       15  
8381                        1  
8382                       27  
8383                       13  
8384                        5  

[8385 rows x 8 columns]

In [56]:
len(pd.unique(df_compP['User_ID']))

5245

In [57]:
len(pd.unique(df_compP['Created At Year']))

1

In [58]:
df_compP.drop('Created At Year', inplace=True, axis=1)

In [59]:
df_compP.rename(columns={'Competition ID': 'Comp_ID'},  inplace = True)

In [60]:
df_compP["User_ID"] = df_compP["User_ID"].astype("string")
df_compP["Created At Month"] = df_compP["Created At Month"].astype("string")

In [61]:
new = df_compP["Created At Month"].copy()
df_compP["User_ID"] = df_compP["User_ID"].str.cat(new, sep ="_Month_")

In [62]:
df_compP.drop('Created At Month', inplace=True, axis=1)

# MERGE 2

In [63]:
result2 = pd.merge(df_compP, df_comp, how="outer", on= 'Comp_ID')

In [64]:
result2 = result2[result2['User_ID'].notna()]

In [65]:
result2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8385 entries, 0 to 8384
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Comp_ID                      8385 non-null   object 
 1   Participant Type             8385 non-null   float64
 2   Successful Submission Count  1449 non-null   object 
 3   User_ID                      8385 non-null   string 
 4   Created At time              8385 non-null   object 
 5   Created At Day_of_month      8385 non-null   float64
 6   FeatureA                     8385 non-null   object 
 7   FeatureB                     8385 non-null   object 
 8   FeatureC                     5655 non-null   float64
 9   FeatureD                     8385 non-null   int64  
 10  FeatureE                     8385 non-null   int64  
 11  SecretCode                   8385 non-null   int64  
 12  FeatureF                     8385 non-null   object 
 13  FeatureG          

In [66]:
result2

Comp_ID  Participant Type Successful Submission Count  \
0     ID_WPP3               1.0                         NaN   
1     ID_WPP3               1.0                         NaN   
2     ID_WPP3               1.0                         NaN   
3     ID_WPP3               1.0                         NaN   
4     ID_WPP3               1.0                         NaN   
...       ...               ...                         ...   
8380  ID_CNBR               1.0                         NaN   
8381  ID_208Z               1.0                         NaN   
8382  ID_H3QQ               1.0                         NaN   
8383  ID_7079               1.0                         NaN   
8384  ID_DFKK               1.0                         NaN   

                   User_ID  Created At time  Created At Day_of_month  \
0     ID_40G01FGV_Month_11  19:38:04.689865                     20.0   
1      ID_D5I1M68U_Month_4  21:15:54.617702                      7.0   
2     ID_G23UREIF_Month_11  16:43:35.871761                     30.0   
3     ID_H4DF1YA9_Month_11  17:55:40.888019                     23.0   
4      ID_F840O4ZH_Month_5  09:42:13.812496                     16.0   
...                    ...              ...                      ...   
8380  ID_6RPFZR7I_Month_11  06:38:13.766016                     17.0   
8381   ID_YEZY3ABB_Month_1  14:26:36.511271                      6.0   
8382   ID_GS03UEEX_Month_4  10:40:22.978880                     22.0   
8383   ID_1CY5JAGU_Month_4  04:23:17.682554                     11.0   
8384   ID_2YXKSD1Q_Month_4  15:34:15.045823                      7.0   

       FeatureA  FeatureB  FeatureC  FeatureD  ...  FeatureI  Country_ID  \
0           [1]  [12, 16]       NaN         1  ...       NaN         NaN   
1           [1]  [12, 16]       NaN         1  ...       NaN         NaN   
2           [1]  [12, 16]       NaN         1  ...       NaN         NaN   
3           [1]  [12, 16]       NaN         1  ...       NaN         NaN   
4           [1]  [12, 16]       NaN         1  ...       NaN         NaN   
...         ...       ...       ...       ...  ...       ...         ...   
8380     [2, 7]        []       9.0         1  ...       9.0         NaN   
8381  [1, 5, 4]    [5, 7]       NaN         1  ...       NaN        N6EN   
8382        [2]        []      17.0         1  ...      17.0        4PRY   
8383  [7, 3, 2]      [15]      10.0         1  ...      10.0        G3F0   
8384        [5]      [15]      10.0         1  ...      10.0         NaN   

     End Time time End Time Year End Time Month  End Time Day_of_month  \
0         00:00:00           3.0            9.0                   24.0   
1         00:00:00           3.0            9.0                   24.0   
2         00:00:00           3.0            9.0                   24.0   
3         00:00:00           3.0            9.0                   24.0   
4         00:00:00           3.0            9.0                   24.0   
...            ...           ...            ...                    ...   
8380      00:00:00           3.0           11.0                   20.0   
8381      23:59:00           3.0           12.0                   17.0   
8382      00:00:00           3.0            9.0                   17.0   
8383      23:59:00           3.0            6.0                   29.0   
8384      23:59:00           2.0            2.0                    4.0   

     Start Time time Start Time Year  Start Time Month  \
0           00:00:00               4                 6   
1           00:00:00               4                 6   
2           00:00:00               4                 6   
3           00:00:00               4                 6   
4           00:00:00               4                 6   
...              ...             ...               ...   
8380        00:00:00               3                 8   
8381        00:00:00               4                 7   
8382        00:00:00               4                 5   
83

In [67]:
df_compP.rename(columns={'Created At time': 'Comp_participation_time'},  inplace = True)

In [68]:
df_compP.rename(columns={'Created At Day_of_month': 'Comp_participation_day'},  inplace = True)

In [69]:
df_compP.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8385 entries, 0 to 8384
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype 
---  ------                       --------------  ----- 
 0   Comp_ID                      8385 non-null   object
 1   Participant Type             8385 non-null   int64 
 2   Successful Submission Count  1449 non-null   object
 3   User_ID                      8385 non-null   string
 4   Comp_participation_time      8385 non-null   object
 5   Comp_participation_day       8385 non-null   int64 
dtypes: int64(2), object(3), string(1)
memory usage: 393.2+ KB


In [70]:
result2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8385 entries, 0 to 8384
Data columns (total 25 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Comp_ID                      8385 non-null   object 
 1   Participant Type             8385 non-null   float64
 2   Successful Submission Count  1449 non-null   object 
 3   User_ID                      8385 non-null   string 
 4   Created At time              8385 non-null   object 
 5   Created At Day_of_month      8385 non-null   float64
 6   FeatureA                     8385 non-null   object 
 7   FeatureB                     8385 non-null   object 
 8   FeatureC                     5655 non-null   float64
 9   FeatureD                     8385 non-null   int64  
 10  FeatureE                     8385 non-null   int64  
 11  SecretCode                   8385 non-null   int64  
 12  FeatureF                     8385 non-null   object 
 13  FeatureG          

# USERS

In [71]:
df_user = pd.read_csv('Users.csv')

In [72]:
df_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12413 entries, 0 to 12412
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   FeatureX                 12413 non-null  int64 
 1   FeatureY                 12413 non-null  int64 
 2   User_ID                  12413 non-null  object
 3   Countries_ID             6531 non-null   object
 4   Created At time          12413 non-null  object
 5   Created At Year          12413 non-null  int64 
 6   Created At Month         12413 non-null  int64 
 7   Created At Day_of_month  12413 non-null  int64 
dtypes: int64(5), object(3)
memory usage: 775.9+ KB


In [73]:
df_user

FeatureX  FeatureY      User_ID Countries_ID  Created At time  \
0             0         0  ID_DC6S4E9O         X9GR  19:33:13.663391   
1             1         0  ID_E8S97OUT         X9GR  22:18:18.228921   
2             0         0  ID_QZ1HASL3         X9GR  23:13:03.266635   
3             1         0  ID_SDV9Q3E9         X9GR  09:50:09.697573   
4             1         0  ID_W942LN7F         X9GR  13:33:06.531662   
...         ...       ...          ...          ...              ...   
12408         0         1  ID_C5393PD0         7DKX  05:02:39.352427   
12409         0         1  ID_QX7XRT0C         K4DG  02:50:19.027320   
12410         0         1  ID_RGN2RK66         ONON  22:06:33.713692   
12411         0         0  ID_XZS1QE0W         3YQR  06:56:02.570173   
12412         0         1  ID_8K4FGJYO         G4PG  10:22:54.369939   

       Created At Year  Created At Month  Created At Day_of_month  
0                    1                 1                       16  
1                    1                12                       27  
2                    1                 1                        1  
3                    1                12                       27  
4                    1                 1                       16  
...                ...               ...                      ...  
12408                1                11                        6  
12409                1                 3                       25  
12410                1                12                        7  
12411                1                 5                       27  
12412                1                12                        5  

[12413 rows x 8 columns]

In [74]:
len(pd.unique(df_user['User_ID']))

12413

In [75]:
len(pd.unique(df_user['Created At Year']))

1

In [76]:
df_user.drop('Created At Year', inplace=True, axis=1)

In [77]:
df_user["User_ID"] = df_user["User_ID"].astype("string")
df_user["Created At Month"] = df_user["Created At Month"].astype("string")

In [78]:
new = df_user["Created At Month"].copy()
df_user["User_ID"] = df_user["User_ID"].str.cat(new, sep ="_Month_")

In [79]:
df_user.rename(columns={'Created At Month': 'User sign-in month'},  inplace = True)

In [80]:
df_user.rename(columns={'Created At time': 'User sign-in time'},  inplace = True)

In [81]:
df_user.rename(columns={'Created At Day_of_month': 'User sign-in day'},  inplace = True)

In [82]:
df_user

FeatureX  FeatureY               User_ID Countries_ID  \
0             0         0   ID_DC6S4E9O_Month_1         X9GR   
1             1         0  ID_E8S97OUT_Month_12         X9GR   
2             0         0   ID_QZ1HASL3_Month_1         X9GR   
3             1         0  ID_SDV9Q3E9_Month_12         X9GR   
4             1         0   ID_W942LN7F_Month_1         X9GR   
...         ...       ...                   ...          ...   
12408         0         1  ID_C5393PD0_Month_11         7DKX   
12409         0         1   ID_QX7XRT0C_Month_3         K4DG   
12410         0         1  ID_RGN2RK66_Month_12         ONON   
12411         0         0   ID_XZS1QE0W_Month_5         3YQR   
12412         0         1  ID_8K4FGJYO_Month_12         G4PG   

      User sign-in time User sign-in month  User sign-in day  
0       19:33:13.663391                  1                16  
1       22:18:18.228921                 12                27  
2       23:13:03.266635                  1                 1  
3       09:50:09.697573                 12                27  
4       13:33:06.531662                  1                16  
...                 ...                ...               ...  
12408   05:02:39.352427                 11                 6  
12409   02:50:19.027320                  3                25  
12410   22:06:33.713692                 12                 7  
12411   06:56:02.570173                  5                27  
12412   10:22:54.369939                 12                 5  

[12413 rows x 7 columns]

# MERGE 3

In [83]:
result3 = pd.merge(df_userAct, df_user, how="outer", on= 'User_ID')

In [84]:
result3

User_ID datetime time  datetime Day_of_month  count_UA  \
0       ID_000H9XOP_Month_5      16:18:22                   26.0       6.0   
1       ID_003YJHQA_Month_4      11:31:30                   12.0      11.0   
2       ID_004UKSJV_Month_1      09:17:09                   15.0       1.0   
3      ID_004UKSJV_Month_12      10:51:58                   29.0      11.0   
4       ID_008D2J6C_Month_1      10:44:55                   15.0      10.0   
...                     ...           ...                    ...       ...   
17186   ID_Y02FKZWI_Month_3           NaN                    NaN       NaN   
17187  ID_FDOGWALS_Month_11           NaN                    NaN       NaN   
17188   ID_YJCY8FF5_Month_5           NaN                    NaN       NaN   
17189   ID_QDL8A9FQ_Month_4           NaN                    NaN       NaN   
17190  ID_C5393PD0_Month_11           NaN                    NaN       NaN   

       FeatureX  FeatureY Countries_ID User sign-in time User sign-in month  \
0           0.0       1.0          NaN   15:18:11.439200                  5   
1           0.0       1.0         GYYX   10:30:32.261855                  4   
2           NaN       NaN          NaN               NaN               <NA>   
3           0.0       0.0         IFO5   08:32:14.997443                 12   
4           0.0       0.0         GYYX   09:42:39.695313                  1   
...         ...       ...          ...               ...                ...   
17186       0.0       0.0         7JT1   04:04:35.100180                  3   
17187       0.0       0.0         UKC2   13:30:49.814791                 11   
17188       0.0       0.0         H801   15:54:12.676400                  5   
17189       0.0       0.0         NRDP   09:49:35.535847                  4   
17190       0.0       1.0         7DKX   05:02:39.352427                 11   

       User sign-in day  
0                  22.0  
1                  12.0  
2                   NaN  
3                  28.0  
4                   7.0  
...                 ...  
17186              26.0  
17187               5.0  
17188              11.0  
17189              28.0  
17190               6.0  

[17191 rows x 10 columns]

# MERGE 4

In [85]:
result4 = pd.merge(result1, result2, how="outer", on= 'User_ID')

In [86]:
result4

Competition ID  Personal  Theme    Disc_ID               User_ID  \
0     GeneralDiscussion       1.0    NaN  ID_0BK7TH  ID_AAGFVLHH_Month_12   
1     GeneralDiscussion       1.0    NaN  ID_ZFJ9J7  ID_0AJGQILU_Month_12   
2     GeneralDiscussion       1.0    NaN  ID_ME45XX   ID_U90KK6KL_Month_2   
3     GeneralDiscussion       1.0    NaN  ID_ME45XX   ID_U90KK6KL_Month_2   
4     GeneralDiscussion       1.0    NaN  ID_ME45XX   ID_U90KK6KL_Month_2   
...                 ...       ...    ...        ...                   ...   
9922                NaN       NaN    NaN        NaN   ID_B3CQS9BQ_Month_3   
9923                NaN       NaN    NaN        NaN  ID_6RPFZR7I_Month_11   
9924                NaN       NaN    NaN        NaN   ID_YEZY3ABB_Month_1   
9925                NaN       NaN    NaN        NaN   ID_GS03UEEX_Month_4   
9926                NaN       NaN    NaN        NaN   ID_1CY5JAGU_Month_4   

      Discussion_time  Discussion_year Discussion_month  Discussion_day  \
0     19:48:26.862175              1.0               12            27.0   
1     09:37:52.039526              1.0               12            20.0   
2     17:50:33.894800              1.0                2             9.0   
3     17:50:33.894800              1.0                2             9.0   
4     17:50:33.894800              1.0                2             9.0   
...               ...              ...              ...             ...   
9922              NaN              NaN             <NA>             NaN   
9923              NaN              NaN             <NA>             NaN   
9924              NaN              NaN             <NA>             NaN   
9925              NaN              NaN             <NA>             NaN   
9926              NaN              NaN             <NA>             NaN   

     comment_time  ...  FeatureI Country_ID  End Time time End Time Year  \
0             NaN  ...      31.0       X9GR       22:59:00           1.0   
1             NaN  ...       NaN        NaN            NaN           NaN   
2             NaN  ...      29.0        NaN       23:59:00           1.0   
3             NaN  ...      28.0       YSLJ       23:59:00           1.0   
4             NaN  ...      28.0       YSLJ       12:00:00           1.0   
...           ...  ...       ...        ...            ...           ...   
9922          NaN  ...      15.0        NaN       23:59:00           2.0   
9923          NaN  ...       9.0        NaN       00:00:00           3.0   
9924          NaN  ...       NaN       N6EN       23:59:00           3.0   
9925          NaN  ...      17.0       4PRY       00:00:00           3.0   
9926          NaN  ...      10.0       G3F0       23:59:00           3.0   

     End Time Month  End Time Day_of_month Start Time time Start Time Year  \
0               2.0                    3.0        22:59:00             1.0   
1               NaN                    NaN             NaN             NaN   
2               3.0                   28.0        06:00:00             1.0   
3               3.0                    7.0        08:00:00             1.0   
4               2.0                   10.0        09:10:00             1.0   
...             ...                    ...             ...             ...   
9922            3.0                   29.0        06:00:00             2.0   
9923           11.0                   20.0        00:00:00             3.0   
9924           12.0                   17.0        00:00:00             4.0   
9925            9.0                   17.0        00:00:00             4.0   
9926            6.0                   29.0        06:00:00             3.0   

      Start Time Month  Start Time Day_of_month  
0                 12.0                     28.0  
1                  NaN                      NaN  
2                 12.0                     24.0  
3                  2.0                      7.0  
4                  2.0                      9.0  
...                ...           

In [87]:
result4.rename(columns={'Created At time_y': 'comment_time'},  inplace = True)

In [88]:
result4.rename(columns={'Created At Day_of_month_y': 'comment_month'},  inplace = True)

In [89]:
result4.rename(columns={'End Time time': 'competition_ended_time'},  inplace = True)

In [90]:
result4.rename(columns={'End Time Year': 'competition_ended_year'},  inplace = True)

In [91]:
result4.rename(columns={'End Time Month': 'competition_ended_month'},  inplace = True)

In [92]:
result4.rename(columns={'End Time Day_of_month': 'competition_ended_day'},  inplace = True)

In [93]:
result4.rename(columns={'Start Time time': 'competition_started_time'},  inplace = True)

In [94]:
result4.rename(columns={'Start Time Year': 'competition_started_year'},  inplace = True)

In [95]:
result4.rename(columns={'Start Time Month': 'competition_started_month'},  inplace = True)

In [96]:
result4.rename(columns={'Start Time Day_of_month': 'competition_started_day'},  inplace = True)

In [97]:
result4.rename(columns={'Created At Day_of_month': 'competition_enrollment_day'},  inplace = True)

In [98]:
result4.rename(columns={'Created At time': 'competition_enrollment_time'},  inplace = True)

In [99]:
result4.drop('Discussion_year', inplace=True, axis=1)

In [100]:
result4.drop('Discussion_month', inplace=True, axis=1)

In [101]:
result4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9927 entries, 0 to 9926
Data columns (total 33 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   Competition ID               2305 non-null   object 
 1   Personal                     2305 non-null   float64
 2   Theme                        272 non-null    float64
 3   Disc_ID                      2891 non-null   object 
 4   User_ID                      9927 non-null   string 
 5   Discussion_time              2305 non-null   object 
 6   Discussion_day               2305 non-null   float64
 7   comment_time                 708 non-null    object 
 8   comment_day                  708 non-null    float64
 9   Comp_ID                      9300 non-null   object 
 10  Participant Type             9300 non-null   float64
 11  Successful Submission Count  1813 non-null   object 
 12  competition_enrollment_time  9300 non-null   object 
 13  competition_enroll

In [102]:
result4

Competition ID  Personal  Theme    Disc_ID               User_ID  \
0     GeneralDiscussion       1.0    NaN  ID_0BK7TH  ID_AAGFVLHH_Month_12   
1     GeneralDiscussion       1.0    NaN  ID_ZFJ9J7  ID_0AJGQILU_Month_12   
2     GeneralDiscussion       1.0    NaN  ID_ME45XX   ID_U90KK6KL_Month_2   
3     GeneralDiscussion       1.0    NaN  ID_ME45XX   ID_U90KK6KL_Month_2   
4     GeneralDiscussion       1.0    NaN  ID_ME45XX   ID_U90KK6KL_Month_2   
...                 ...       ...    ...        ...                   ...   
9922                NaN       NaN    NaN        NaN   ID_B3CQS9BQ_Month_3   
9923                NaN       NaN    NaN        NaN  ID_6RPFZR7I_Month_11   
9924                NaN       NaN    NaN        NaN   ID_YEZY3ABB_Month_1   
9925                NaN       NaN    NaN        NaN   ID_GS03UEEX_Month_4   
9926                NaN       NaN    NaN        NaN   ID_1CY5JAGU_Month_4   

      Discussion_time  Discussion_day comment_time  comment_day  Comp_ID  ...  \
0     19:48:26.862175            27.0          NaN          NaN  ID_528W  ...   
1     09:37:52.039526            20.0          NaN          NaN      NaN  ...   
2     17:50:33.894800             9.0          NaN          NaN  ID_JRC2  ...   
3     17:50:33.894800             9.0          NaN          NaN  ID_7CF2  ...   
4     17:50:33.894800             9.0          NaN          NaN  ID_45W9  ...   
...               ...             ...          ...          ...      ...  ...   
9922              NaN             NaN          NaN          NaN  ID_UCC7  ...   
9923              NaN             NaN          NaN          NaN  ID_CNBR  ...   
9924              NaN             NaN          NaN          NaN  ID_208Z  ...   
9925              NaN             NaN          NaN          NaN  ID_H3QQ  ...   
9926              NaN             NaN          NaN          NaN  ID_7079  ...   

      FeatureI Country_ID competition_ended_time  competition_ended_year  \
0         31.0       X9GR               22:59:00                     1.0   
1          NaN        NaN                    NaN                     NaN   
2         29.0        NaN               23:59:00                     1.0   
3         28.0       YSLJ               23:59:00                     1.0   
4         28.0       YSLJ               12:00:00                     1.0   
...        ...        ...                    ...                     ...   
9922      15.0        NaN               23:59:00                     2.0   
9923       9.0        NaN               00:00:00                     3.0   
9924       NaN       N6EN               23:59:00                     3.0   
9925      17.0       4PRY               00:00:00                     3.0   
9926      10.0       G3F0               23:59:00                     3.0   

     competition_ended_month competition_ended_day  competition_started_time  \
0                        2.0                   3.0                  22:59:00   
1                        NaN                   NaN                       NaN   
2                        3.0                  28.0                  06:00:00   
3                        3.0                   7.0                  08:00:00   
4                        2.0                  10.0                  09:10:00   
...                      ...                   ...                       ...   
9922                     3.0                  29.0                  06:00:00   
9923                    11.0                  20.0                  00:00:00   
9924                    12.0                  17.0                  00:00:00   
9925                     9.0                  17.0                  00:00:00   
9926                     6.0                  29.0                  06:00:00   

      competition_started_year  competition_started_month  \
0                          1.0                       12.0   
1                          NaN                        NaN   
2                          1.0                       1

# MERGE 5

In [103]:
df_final = pd.merge(result4, result3, how="outer", on= 'User_ID')

In [104]:
df_final.drop('Competition ID', inplace=True, axis=1)

In [105]:
df_final.drop('Disc_ID', inplace=True, axis=1)

In [106]:
df_final.drop('Comp_ID', inplace=True, axis=1)

In [107]:
df_final["Country_ID"].unique()

array(['X9GR', nan, 'YSLJ', 'G3F0', 'GYYX', '03GB', 'ZEWU', 'DYYF',
       'KYT4', 'ISIQ', 'N6EN', 'EGI9', 'H03V', 'SE4K', '4PRY'],
      dtype=object)

In [108]:
df_final.drop('Countries_ID', inplace=True, axis=1)

In [109]:
first_column = df_final.pop('User_ID')

In [110]:
df_final.insert(0, 'User_ID', first_column)

In [111]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21002 entries, 0 to 21001
Data columns (total 38 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   User_ID                      21002 non-null  object 
 1   Personal                     2305 non-null   float64
 2   Theme                        272 non-null    float64
 3   Discussion_time              2305 non-null   object 
 4   Discussion_day               2305 non-null   float64
 5   comment_time                 708 non-null    object 
 6   comment_day                  708 non-null    float64
 7   Participant Type             9300 non-null   float64
 8   Successful Submission Count  1813 non-null   object 
 9   competition_enrollment_time  9300 non-null   object 
 10  competition_enrollment_day   9300 non-null   float64
 11  FeatureA                     9300 non-null   object 
 12  FeatureB                     9300 non-null   object 
 13  FeatureC        

In [112]:
df_final

User_ID  Personal  Theme  Discussion_time  Discussion_day  \
0      ID_AAGFVLHH_Month_12       1.0    NaN  19:48:26.862175            27.0   
1      ID_0AJGQILU_Month_12       1.0    NaN  09:37:52.039526            20.0   
2       ID_U90KK6KL_Month_2       1.0    NaN  17:50:33.894800             9.0   
3       ID_U90KK6KL_Month_2       1.0    NaN  17:50:33.894800             9.0   
4       ID_U90KK6KL_Month_2       1.0    NaN  17:50:33.894800             9.0   
...                     ...       ...    ...              ...             ...   
20997   ID_Y02FKZWI_Month_3       NaN    NaN              NaN             NaN   
20998  ID_FDOGWALS_Month_11       NaN    NaN              NaN             NaN   
20999   ID_YJCY8FF5_Month_5       NaN    NaN              NaN             NaN   
21000   ID_QDL8A9FQ_Month_4       NaN    NaN              NaN             NaN   
21001  ID_C5393PD0_Month_11       NaN    NaN              NaN             NaN   

      comment_time  comment_day  Participant Type Successful Submission Count  \
0              NaN          NaN               1.0                         NaN   
1              NaN          NaN               NaN                         NaN   
2              NaN          NaN               1.0                         NaN   
3              NaN          NaN               1.0                         NaN   
4              NaN          NaN               1.0                         NaN   
...            ...          ...               ...                         ...   
20997          NaN          NaN               NaN                         NaN   
20998          NaN          NaN               NaN                         NaN   
20999          NaN          NaN               NaN                         NaN   
21000          NaN          NaN               NaN                         NaN   
21001          NaN          NaN               NaN                         NaN   

      competition_enrollment_time  ...  competition_started_month  \
0                 10:53:52.558030  ...                       12.0   
1                             NaN  ...                        NaN   
2                 18:57:59.998938  ...                       12.0   
3                 18:49:47.531900  ...                        2.0   
4                 15:34:35.872471  ...                        2.0   
...                           ...  ...                        ...   
20997                         NaN  ...                        NaN   
20998                         NaN  ...                        NaN   
20999                         NaN  ...                        NaN   
21000                         NaN  ...                        NaN   
21001                         NaN  ...                        NaN   

      competition_started_day datetime time  datetime Day_of_month  count_UA  \
0                        28.0      20:52:03                   28.0      35.0   
1                         NaN      10:38:23                   20.0      14.0   
2                        24.0      21:37:16                   24.0      96.0   
3                         7.0      21:37:16                   24.0      96.0   
4                         9.0      21:37:16                   24.0      96.0   
...                       ...           ...                    ...       ...   
20997                     NaN           NaN                    NaN       NaN   
20998                     NaN           NaN                    NaN       NaN   
20999                     NaN           NaN                    NaN       NaN   
21000                     NaN           NaN                    NaN       NaN   
21001                     NaN           NaN                    NaN       NaN   

       FeatureX  FeatureY User sign-in time User sign-in month  \
0           0.0       0.0   08:26:28.847530                 12   
1           0.0       0.0   09:28:59.699371                 12   
2           1.0       1.0   15:29:09.389920                  2   
3           1.0     

# DATA CLEANING AND TRANSFORMATION

In [113]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21002 entries, 0 to 21001
Data columns (total 38 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   User_ID                      21002 non-null  object 
 1   Personal                     2305 non-null   float64
 2   Theme                        272 non-null    float64
 3   Discussion_time              2305 non-null   object 
 4   Discussion_day               2305 non-null   float64
 5   comment_time                 708 non-null    object 
 6   comment_day                  708 non-null    float64
 7   Participant Type             9300 non-null   float64
 8   Successful Submission Count  1813 non-null   object 
 9   competition_enrollment_time  9300 non-null   object 
 10  competition_enrollment_day   9300 non-null   float64
 11  FeatureA                     9300 non-null   object 
 12  FeatureB                     9300 non-null   object 
 13  FeatureC        

In [114]:
df_final

User_ID  Personal  Theme  Discussion_time  Discussion_day  \
0      ID_AAGFVLHH_Month_12       1.0    NaN  19:48:26.862175            27.0   
1      ID_0AJGQILU_Month_12       1.0    NaN  09:37:52.039526            20.0   
2       ID_U90KK6KL_Month_2       1.0    NaN  17:50:33.894800             9.0   
3       ID_U90KK6KL_Month_2       1.0    NaN  17:50:33.894800             9.0   
4       ID_U90KK6KL_Month_2       1.0    NaN  17:50:33.894800             9.0   
...                     ...       ...    ...              ...             ...   
20997   ID_Y02FKZWI_Month_3       NaN    NaN              NaN             NaN   
20998  ID_FDOGWALS_Month_11       NaN    NaN              NaN             NaN   
20999   ID_YJCY8FF5_Month_5       NaN    NaN              NaN             NaN   
21000   ID_QDL8A9FQ_Month_4       NaN    NaN              NaN             NaN   
21001  ID_C5393PD0_Month_11       NaN    NaN              NaN             NaN   

      comment_time  comment_day  Participant Type Successful Submission Count  \
0              NaN          NaN               1.0                         NaN   
1              NaN          NaN               NaN                         NaN   
2              NaN          NaN               1.0                         NaN   
3              NaN          NaN               1.0                         NaN   
4              NaN          NaN               1.0                         NaN   
...            ...          ...               ...                         ...   
20997          NaN          NaN               NaN                         NaN   
20998          NaN          NaN               NaN                         NaN   
20999          NaN          NaN               NaN                         NaN   
21000          NaN          NaN               NaN                         NaN   
21001          NaN          NaN               NaN                         NaN   

      competition_enrollment_time  ...  competition_started_month  \
0                 10:53:52.558030  ...                       12.0   
1                             NaN  ...                        NaN   
2                 18:57:59.998938  ...                       12.0   
3                 18:49:47.531900  ...                        2.0   
4                 15:34:35.872471  ...                        2.0   
...                           ...  ...                        ...   
20997                         NaN  ...                        NaN   
20998                         NaN  ...                        NaN   
20999                         NaN  ...                        NaN   
21000                         NaN  ...                        NaN   
21001                         NaN  ...                        NaN   

      competition_started_day datetime time  datetime Day_of_month  count_UA  \
0                        28.0      20:52:03                   28.0      35.0   
1                         NaN      10:38:23                   20.0      14.0   
2                        24.0      21:37:16                   24.0      96.0   
3                         7.0      21:37:16                   24.0      96.0   
4                         9.0      21:37:16                   24.0      96.0   
...                       ...           ...                    ...       ...   
20997                     NaN           NaN                    NaN       NaN   
20998                     NaN           NaN                    NaN       NaN   
20999                     NaN           NaN                    NaN       NaN   
21000                     NaN           NaN                    NaN       NaN   
21001                     NaN           NaN                    NaN       NaN   

       FeatureX  FeatureY User sign-in time User sign-in month  \
0           0.0       0.0   08:26:28.847530                 12   
1           0.0       0.0   09:28:59.699371                 12   
2           1.0       1.0   15:29:09.389920                  2   
3           1.0     

In [115]:
df_final.shape

(21002, 38)

In [116]:
df_final["Personal"].unique()

array([ 1.,  0., nan])

In [117]:
df_final['Personal'].fillna(-1, inplace = True)
df_final["Personal"].unique()

array([ 1.,  0., -1.])

In [118]:
df_final["Theme"].unique()

array([nan,  3.,  1.,  4.,  5.,  2.])

In [119]:
df_final['Theme'].fillna(-1, inplace = True)
df_final["Theme"].unique()

array([-1.,  3.,  1.,  4.,  5.,  2.])

In [120]:
df_final["Discussion_time"]= df_final["Discussion_time"].astype("string")
#df_user["Created At Month"] = df_user["Created At Month"].astype("string")

In [121]:
df_final['Discussion Hour'] = df_final['Discussion_time'].str[0:2]

In [122]:
df_final['Discussion Minute'] = df_final['Discussion_time'].str[3:5]

In [123]:
df_final['Discussion Second'] = df_final['Discussion_time'].str[6:]

In [124]:
df_final['Discussion Hour'].isna().sum()

18697

In [125]:
df_final['Discussion Hour'].unique()

<StringArray>
['19', '09', '17', '07', '18', '00', '01', '05', '23', '04', '22', '14', '15',
 '16', '11', '13', <NA>, '20', '06', '03', '10', '08', '21', '12', '02']
Length: 25, dtype: string

In [126]:
df_final['Discussion Hour'].fillna('-1', inplace = True)

In [127]:
df_final['Discussion Minute'].isna().sum()

18697

In [128]:
df_final['Discussion Minute'].unique()

<StringArray>
['48', '37', '50', '57', '56', '20', '30', '46', '40', '08', '06', '38', '33',
 '23', '24', '43', '29', '16', '15', '55', '17', '36', '12', <NA>, '54', '02',
 '51', '09', '25', '49', '01', '04', '53', '11', '45', '31', '22', '26', '18',
 '35', '03', '27', '47', '39', '14', '42', '59', '52', '32', '00', '34', '41',
 '21', '28', '10', '13', '19', '07', '44', '58', '05']
Length: 61, dtype: string

In [129]:
df_final['Discussion Minute'].fillna('-1', inplace = True)

In [130]:
df_final['Discussion Second'].isna().sum()

18697

In [131]:
df_final['Discussion Second'].unique()

<StringArray>
['26.862175', '52.039526', '33.894800', '55.178845', '13.041893', '26.568254',
 '29.783050', '27.612805', '35.086345', '28.053523',
 ...
 '45.333845', '35.875145', '42.357376', '57.964075', '32.417637', '31.081484',
 '11.201934', '31.578153', '59.313759', '04.296241']
Length: 1440, dtype: string

In [132]:
df_final['Discussion Second'].fillna('-1', inplace = True)

In [133]:
df_final['Discussion_day'].fillna('-1', inplace = True)

In [134]:
df_final.drop('Discussion_time', axis=1, inplace=True)

In [135]:
df_final["comment_time"].unique()

array([nan, '16:18:44.841697', '13:28:47.950841', '18:42:17.362333',
       '17:30:40.566763', '18:57:54.540062', '00:30:14.803404',
       '06:11:25.314720', '15:55:00.421045', '06:06:14.246596',
       '05:36:20.487510', '06:12:27.399835', '13:16:21.738170',
       '20:01:15.324733', '05:31:23.850937', '07:04:23.607974',
       '07:52:06.787861', '07:51:36.568373', '16:54:57.277821',
       '04:11:08.952569', '04:10:31.876264', '10:51:58.057413',
       '04:10:39.639913', '04:12:08.642788', '04:10:06.110932',
       '14:17:12.801487', '14:02:51.545438', '10:55:22.419127',
       '17:08:30.010734', '10:30:24.835888', '12:52:45.129685',
       '13:47:11.086669', '13:56:55.287683', '10:29:21.336571',
       '12:57:35.809671', '16:32:19.323816', '12:53:45.851203',
       '07:40:52.210103', '22:49:39.579835', '18:16:38.436559',
       '21:53:36.148890', '10:50:42.816479', '13:05:39.826050',
       '13:03:29.318252', '10:44:00.954715', '10:44:59.922062',
       '10:33:57.026183', '13:08:16

In [136]:
df_final['Comment Hour'] = df_final['comment_time'].str[0:2]

In [137]:
df_final['Comment Minute'] = df_final['comment_time'].str[3:5]

In [138]:
df_final['Comment Second'] = df_final['comment_time'].str[6:]

In [139]:
df_final.rename(columns={'competition_enrollement_day': 'competition_enrollment_day'},  inplace = True)

In [140]:
df_final['Comment Hour'].isna().sum()

20294

In [141]:
df_final['Comment Hour'].unique()

array([nan, '16', '13', '18', '17', '00', '06', '15', '05', '20', '07',
       '04', '10', '14', '12', '22', '21', '19', '08', '11', '23', '09',
       '01', '02', '03'], dtype=object)

In [142]:
df_final['Comment Hour'].fillna(-1, inplace = True)

In [143]:
df_final['Comment Minute'].isna().sum()

20294

In [144]:
df_final['Comment Minute'].unique()

array([nan, '18', '28', '42', '30', '57', '11', '55', '06', '36', '12',
       '16', '01', '31', '04', '52', '51', '54', '10', '17', '02', '08',
       '47', '56', '29', '32', '53', '40', '49', '50', '05', '03', '44',
       '33', '27', '38', '59', '37', '07', '35', '15', '41', '00', '09',
       '14', '13', '58', '19', '22', '20', '34', '25', '39', '24', '43',
       '21', '23', '48', '26', '45', '46'], dtype=object)

In [145]:
df_final['Comment Minute'].fillna(-1, inplace = True)

In [146]:
df_final['Comment Second'].isna().sum()

20294

In [147]:
df_final['Comment Second'].unique()

array([nan, '44.841697', '47.950841', '17.362333', '40.566763',
       '54.540062', '14.803404', '25.314720', '00.421045', '14.246596',
       '20.487510', '27.399835', '21.738170', '15.324733', '23.850937',
       '23.607974', '06.787861', '36.568373', '57.277821', '08.952569',
       '31.876264', '58.057413', '39.639913', '08.642788', '06.110932',
       '12.801487', '51.545438', '22.419127', '30.010734', '24.835888',
       '45.129685', '11.086669', '55.287683', '21.336571', '35.809671',
       '19.323816', '45.851203', '52.210103', '39.579835', '38.436559',
       '36.148890', '42.816479', '39.826050', '29.318252', '00.954715',
       '59.922062', '57.026183', '16.641999', '29.436142', '30.888350',
       '54.620654', '15.801995', '18.173805', '10.991962', '48.364815',
       '30.305110', '12.616747', '28.299566', '50.084484', '39.055834',
       '20.448348', '41.962152', '35.234312', '33.090172', '11.017713',
       '11.040784', '52.068486', '28.808367', '14.135013', '47.479774',


In [148]:
df_final['Comment Second'].fillna(-1, inplace = True)

In [149]:
df_final['comment_day'].unique()

array([nan, 11.,  3.,  5., 23., 19., 20., 14., 29.,  1., 16.,  9., 13.,
       28.,  7., 24., 21., 15., 12., 17., 26., 25., 22., 18., 31.,  6.,
        8.])

In [150]:
df_final['comment_day'].fillna(0, inplace = True)

In [151]:
df_final.drop('comment_time', axis=1, inplace=True)

In starting 6 columns, we can't use any other method to fill because majority of the columns are null and if first row is only null means we cant use interpolate or padding methods.

We are using average beacuse less rows are missing and since there are no teams participating in teams in the competation the values reamins 1.

In [152]:
df_final['Participant Type'].isna().sum()

11702

In [153]:
df_final["Participant Type"].unique()

array([ 1., nan])

In [154]:
df_final['Participant Type'].fillna(0, inplace = True)

In [155]:
df_final["Successful Submission Count"].unique()

array([nan, 'count 10', 'count 8', 'count 7', 'count 9', 'count 6',
       'count 3', 'count 5', 'count 4'], dtype=object)

In [156]:
df_final['Successful Submission Count'].isna().sum()

19189

In [157]:
df_final['Successful Submission Count'] = df_final['Successful Submission Count'].str[6:]

In [158]:
df_final['Successful Submission Count'].fillna(0, inplace = True)

In [159]:
df_final['competition enrollment hour'] = df_final['competition_enrollment_time'].str[0:2]

In [160]:
df_final['competition enrollment minute'] = df_final['competition_enrollment_time'].str[3:5]

In [161]:
df_final['competition enrollment second'] = df_final['competition_enrollment_time'].str[6:]

In [162]:
df_final['competition enrollment hour'].isna().sum()

11702

In [163]:
df_final['competition enrollment hour'].unique()

array(['10', nan, '18', '15', '01', '16', '17', '22', '13', '02', '05',
       '07', '08', '19', '12', '09', '20', '21', '03', '23', '14', '06',
       '11', '04', '00'], dtype=object)

In [164]:
df_final['competition enrollment hour'].fillna(-1, inplace = True)

In [165]:
df_final['competition enrollment minute'].isna().sum()

11702

In [166]:
df_final['competition enrollment minute'].unique()

array(['53', nan, '57', '49', '34', '07', '22', '59', '18', '45', '19',
       '55', '44', '15', '12', '29', '50', '51', '30', '38', '37', '41',
       '42', '47', '36', '09', '01', '00', '02', '11', '39', '08', '28',
       '23', '46', '26', '40', '25', '43', '33', '31', '16', '06', '32',
       '13', '20', '54', '58', '24', '04', '17', '21', '35', '48', '52',
       '05', '03', '10', '27', '56', '14'], dtype=object)

In [167]:
df_final['competition enrollment minute'].fillna(-1, inplace = True)

In [168]:
df_final['competition enrollment second'].isna().sum()

11702

In [169]:
df_final['competition enrollment second'].unique()

array(['52.558030', nan, '59.998938', ..., '36.511271', '22.978880',
       '17.682554'], dtype=object)

In [170]:
df_final['competition enrollment second'].fillna(-1, inplace = True)

In [171]:
df_final.drop('competition_enrollment_time', axis=1, inplace=True)

In [172]:
df_final['competition_enrollment_day'].unique()

array([28., nan, 12.,  8., 17., 19.,  9., 29., 11.,  7.,  1.,  2., 30.,
       13., 21., 31.,  3., 10., 20., 26., 27., 16., 14., 25., 23.,  4.,
        5., 15., 18., 24., 22.,  6.])

In [173]:
df_final['competition_enrollment_day'].fillna(0, inplace = True)

In [174]:
df_final['FeatureA'].isna().sum()

11702

In [175]:
df_final['FeatureA'].unique()

array(['[]', nan, '[1]', '[2]', '[1, 7]', '[5]', '[4]', '[1, 6]',
       '[2, 4]', '[7]', '[3]', '[3, 2]', '[4, 2]', '[3, 7]', '[2, 3]',
       '[4, 7, 2]', '[1, 9]', '[2, 4, 5]', '[5, 4]', '[5, 2]',
       '[1, 4, 5]', '[8]', '[2, 7]', '[1, 5, 4]', '[7, 3, 2]'],
      dtype=object)

In [176]:
df_final['FeatureA'].fillna('[-1]', inplace = True)

In [177]:
df_final['FeatureA'] = df_final.FeatureA.map(ast.literal_eval)

In [178]:
df_final['FeatureB'].unique()

array(['[]', nan, '[5]', '[15]', '[9]', '[16]', '[14]', '[7, 5]', '[7]',
       '[2]', '[1]', '[5, 6]', '[6]', '[12, 16]', '[10]', '[12]',
       '[5, 7]', '[14, 7]', '[14, 8]'], dtype=object)

In [179]:
df_final['FeatureB'].fillna('[-1]', inplace = True)

In [180]:
df_final['FeatureB'] = df_final.FeatureB.map(ast.literal_eval)

In [181]:
df_final['FeatureC'].unique()

array([nan, 28.,  4.,  2., 10.,  5., 15., 29.,  1.,  6., 11., 13.,  7.,
       24., 14., 35.,  8.,  9., 31.,  3., 16., 25., 27., 20., 26., 37.,
       12., 18., 17.])

In [182]:
df_final['FeatureC'].fillna(-1, inplace = True)

In [183]:
df_final['FeatureD'].unique()

array([ 0., nan,  1.])

In [184]:
df_final['FeatureD'].fillna(-1, inplace = True)

In [185]:
df_final['FeatureE'].unique()

array([ 3., nan,  2.,  1.])

In [186]:
df_final['FeatureE'].fillna(-1, inplace = True)

In [187]:
df_final['FeatureF'].unique()

array(['[]', nan, '[7]', '[10]', '[1]', '[2]', '[2, 3]', '[3]', '[2, 8]',
       '[15]', '[6]', '[3, 2]', '[1, 5]', '[9]', '[2, 11]', '[1, 12]',
       '[1, 3]', '[2, 13]', '[3, 1]', '[2, 1]', '[8]', '[1, 11]'],
      dtype=object)

In [188]:
df_final['FeatureF'].fillna('[-1]', inplace = True)

In [189]:
df_final['FeatureF'] = df_final.FeatureF.map(ast.literal_eval)

In [190]:
df_final['FeatureG'].unique()

array(['[5]', nan, '[4]', '[3]', '[]', '[5, 3, 4]'], dtype=object)

In [191]:
df_final['FeatureG'].fillna('[-1]', inplace = True)

In [192]:
df_final['FeatureG'] = df_final.FeatureG.map(ast.literal_eval)

In [193]:
df_final['FeatureH'].unique()

array(['[1]', nan, '[]', '[10]', '[2]', '[3, 2]', '[2, 3]', '[3]', '[6]',
       '[7]', '[8, 10]', '[9]', '[1, 3]', '[2, 8]', '[3, 1]', '[2, 1]',
       '[8]'], dtype=object)

In [194]:
df_final['FeatureH'].fillna('[-1]', inplace = True)

In [195]:
df_final['FeatureH'] = df_final.FeatureH.map(ast.literal_eval)

In [196]:
df_final['FeatureI'].unique()

array([31., nan, 29., 28.,  4.,  2., 10.,  5., 15.,  1.,  6., 33., 11.,
       13.,  7., 24., 14., 35.,  8.,  9.,  3., 16., 25., 27., 20., 26.,
       37., 12., 18., 17.])

In [197]:
df_final['FeatureI'].fillna(-1, inplace = True)

In [198]:
df_final['FeatureX'].unique()

array([ 0.,  1., nan])

In [199]:
df_final['FeatureX'].fillna(-1, inplace = True)

In [200]:
df_final['FeatureY'].unique()

array([ 0.,  1., nan,  3.])

In [201]:
df_final['FeatureY'].fillna(-1, inplace = True)

In [ ]:
for i in range(len(df_final)):
    arr = df_final.loc[i, "FeatureA"]
    mean = np.mean(arr)
    df_final.loc[i, "FeatureA"] = mean
    arr = df_final.loc[i, "FeatureB"]
    mean = np.mean(arr)
    df_final.loc[i, "FeatureB"] = mean
    arr = df_final.loc[i, "FeatureF"]
    mean = np.mean(arr)
    df_final.loc[i, "FeatureF"] = mean
    arr = df_final.loc[i, "FeatureG"]
    mean = np.mean(arr)
    df_final.loc[i, "FeatureG"] = mean
    arr = df_final.loc[i, "FeatureH"]
    mean = np.mean(arr)
    df_final.loc[i, "FeatureH"] = mean

In [ ]:
df_final['SecretCode'].isna().sum()

In [203]:
df_final['SecretCode'].unique()

array([ 1., nan,  0.])

In [204]:
df_final['SecretCode'].fillna(-1, inplace = True)

In [205]:
df_final['competition_ended_time'].unique()

array(['22:59:00', nan, '23:59:00', '12:00:00', '11:59:00', '15:00:00',
       '16:00:00', '06:00:00', '23:09:00', '00:00:00', '07:00:00',
       '05:59:00', '14:00:00', '23:30:00', '11:00:00', '02:00:00',
       '18:00:00', '09:30:00'], dtype=object)

In [206]:
df_final['competition ended hour'] = df_final['competition_ended_time'].str[0:2]
df_final['competition ended minute'] = df_final['competition_ended_time'].str[3:5]
df_final['competition ended second'] = df_final['competition_ended_time'].str[6:]

In [424]:
df_final['competition ended hour'].isna().sum()

13916

In [425]:
df_final['competition ended hour'].unique()

array(['22', nan, '23', '12', '11', '15', '16', '06', '00', '07', '05',
       '14', '02', '18', '09'], dtype=object)

In [426]:
df_final['competition ended hour'].fillna(-1, inplace = True)

In [427]:
df_final['competition ended minute'].isna().sum()

13916

In [428]:
df_final['competition ended minute'].unique()

array(['59', nan, '00', '09', '30'], dtype=object)

In [429]:
df_final['competition ended minute'].fillna(-1, inplace = True)

In [430]:
df_final['competition ended second'].isna().sum()

13916

In [431]:
df_final['competition ended second'].unique()

array(['00', nan], dtype=object)

In [432]:
df_final['competition ended second'].fillna(-1, inplace = True)

In [433]:
df_final.drop('competition_ended_time', axis=1, inplace=True)

In [434]:
df_final['competition_ended_year'].unique()

array([1.000e+00,       nan, 2.023e+03, 4.000e+00, 3.000e+00, 2.000e+00,
       5.000e+00])

In [435]:
df_final['competition_ended_year'].fillna(0, inplace = True)

In [436]:
df_final['competition_ended_month'].unique()

array([ 2., nan,  3.,  5.,  7.,  1., 10.,  4.,  9.,  6.,  8., 12., 11.])

In [437]:
df_final['competition_ended_month'].fillna(0, inplace = True)

In [438]:
df_final['competition_ended_day'].unique()

array([ 3., nan, 28.,  7., 10.,  2.,  8., 26., 31.,  4.,  1., 24.,  5.,
       14., 22., 23., 18., 30., 25., 12., 13., 19., 29., 21.,  6., 27.,
       17., 15.,  9., 16., 20.])

In [439]:
df_final['competition_ended_day'].fillna(0, inplace = True)

In [440]:
df_final['competition_started_time'].unique()

array(['22:59:00', nan, '06:00:00', '08:00:00', '09:10:00', '02:00:00',
       '07:00:00', '11:00:00', '05:00:00', '00:00:00', '05:13:00',
       '23:00:00', '10:00:00', '23:59:00', '09:00:00', '00:01:00',
       '10:30:00', '14:00:00', '12:00:00', '13:30:00', '15:00:00',
       '04:00:00', '20:00:00', '09:30:00', '13:00:00', '01:59:00',
       '17:00:00', '05:59:00'], dtype=object)

In [441]:
df_final['competition started hour'] = df_final['competition_started_time'].str[0:2]
df_final['competition started minute'] = df_final['competition_started_time'].str[3:5]
df_final['competition started second'] = df_final['competition_started_time'].str[6:]

In [442]:
df_final['competition started hour'].isna().sum()

11702

In [443]:
df_final['competition started hour'].unique()

array(['22', nan, '06', '08', '09', '02', '07', '11', '05', '00', '23',
       '10', '14', '12', '13', '15', '04', '20', '01', '17'], dtype=object)

In [444]:
df_final['competition started hour'].fillna(-1, inplace = True)

In [445]:
df_final['competition started minute'].isna().sum()

11702

In [446]:
df_final['competition started minute'].unique()

array(['59', nan, '00', '10', '13', '01', '30'], dtype=object)

In [447]:
df_final['competition started minute'].fillna(-1, inplace = True)

In [448]:
df_final['competition started second'].isna().sum()

11702

In [449]:
df_final['competition started second'].unique()

array(['00', nan], dtype=object)

In [450]:
df_final['competition started second'].fillna(-1, inplace = True)

In [451]:
df_final.drop('competition_started_time', axis=1, inplace=True)

In [452]:
df_final['competition_started_year'].unique()

array([ 1., nan,  4.,  3.,  5.,  2.])

In [453]:
df_final['competition_started_year'].fillna(0, inplace = True)

In [454]:
df_final['competition_started_month'].unique()

array([12., nan,  2.,  4.,  5.,  1., 11.,  9.,  3.,  6., 10.,  8.,  7.])

In [455]:
df_final['competition_started_month'].fillna(0, inplace = True)

In [456]:
df_final['competition_started_day'].unique()

array([28., nan, 24.,  7.,  9.,  4., 15.,  5., 23.,  1., 22.,  3., 13.,
       29., 14., 17., 21., 11., 19.,  6., 16.,  2., 20., 30., 26., 27.,
       25., 18., 12.])

In [457]:
df_final['competition_started_day'].fillna(0, inplace = True)

In [458]:
df_final.rename(columns={'datetime time': 'Time user completed action'},  inplace = True)
df_final.rename(columns={'datetime Day_of_month': 'Day last active'},  inplace = True)

In [459]:
df_final['Time user completed action'].unique()

array(['20:52:03', '10:38:23', '21:37:16', ..., '19:19:21', '11:57:10',
       '23:16:34'], dtype=object)

In [460]:
df_final['User sign-in hour'] = df_final['User sign-in time'].str[0:2]
df_final['User sign-in minute'] = df_final['User sign-in time'].str[3:5]
df_final['User sign-in second'] = df_final['User sign-in time'].str[6:]

In [461]:
df_final['User sign-in hour'].isna().sum()

6273

In [462]:
df_final['User sign-in hour'].unique()

array(['08', '09', '15', '19', nan, '17', '20', '05', '22', '13', '07',
       '16', '06', '14', '18', '03', '10', '23', '12', '11', '00', '21',
       '01', '04', '02'], dtype=object)

In [463]:
df_final['User sign-in hour'].fillna(-1, inplace = True)

In [464]:
df_final['User sign-in minute'].isna().sum()

6273

In [465]:
df_final['User sign-in minute'].unique()

array(['26', '28', '29', '25', nan, '21', '19', '48', '55', '37', '08',
       '01', '43', '24', '27', '51', '47', '14', '52', '11', '02', '49',
       '40', '42', '18', '06', '30', '44', '57', '16', '41', '54', '15',
       '12', '32', '17', '23', '03', '20', '31', '10', '46', '33', '36',
       '50', '58', '38', '35', '07', '00', '05', '56', '13', '04', '53',
       '59', '22', '34', '45', '39', '09'], dtype=object)

In [466]:
df_final['User sign-in minute'].fillna(-1, inplace = True)

In [467]:
df_final['User sign-in second'].isna().sum()

6273

In [468]:
df_final['User sign-in second'].unique()

array(['28.847530', '59.699371', '09.389920', ..., '12.676400',
       '35.535847', '39.352427'], dtype=object)

In [469]:
df_final['User sign-in second'].fillna(-1, inplace = True)

In [470]:
df_final.drop('User sign-in time', axis=1, inplace=True)

In [471]:
df_final['Day last active'].unique()

array([28., 20., 24., 27., 29., 31., 26., 30., 15., 21.,  5.,  6., 25.,
       nan,  2., 10., 23.,  9.,  4., 19., 14.,  3.,  7., 16., 11., 18.,
       22., 17.,  8., 12., 13.,  1.])

In [472]:
df_final['competition_started_day'].fillna(0, inplace = True)

In [473]:
df_final['count_UA'].isna().sum()

2984

In [474]:
len(df_final['count_UA'].unique())

270

In [475]:
df_final['count_UA'].fillna(0, inplace = True)

In [476]:
df_final['Comment Hour'].fillna(-1, inplace = True)
df_final['Comment Minute'].fillna(-1, inplace = True)
df_final['Comment Second'].fillna(-1, inplace = True)

In [477]:
df_final['User sign-in day'].isna().sum()

6273

In [478]:
df_final['User sign-in day'].unique()

array([20.,  8., 27., nan, 13., 21., 31.,  3., 29., 17., 14.,  6.,  5.,
       23., 26.,  4., 16., 28., 10., 24., 18., 22., 30.,  7.,  1., 15.,
       25., 12.,  2.,  9., 19., 11.])

In [479]:
df_final['User sign-in day'].fillna(0, inplace = True)

In [480]:
df_final['Time user completed action in hour'] = df_final['Time user completed action'].str[0:2]
df_final['Time user completed action in minute'] = df_final['Time user completed action'].str[3:5]
df_final['Time user completed action in second'] = df_final['Time user completed action'].str[6:]

In [493]:
df_final.drop('Time user completed action', axis=1, inplace=True)

In [484]:
df_final['Discussion Hour'] = pd.to_numeric(df_final['Discussion Hour'])
df_final['Discussion Minute'] = pd.to_numeric(df_final['Discussion Minute'])
df_final['Discussion Second'] = pd.to_numeric(df_final['Discussion Second'])
df_final['Discussion Day'] = pd.to_numeric(df_final['Discussion Second'])
df_final['Comment Hour'] = pd.to_numeric(df_final['Comment Hour'])
df_final['Comment Minute'] = pd.to_numeric(df_final['Comment Minute'])
df_final['Comment Second'] = pd.to_numeric(df_final['Comment Second'])
df_final['competition enrollment hour'] = pd.to_numeric(df_final['competition enrollment hour'])
df_final['competition enrollment minute'] = pd.to_numeric(df_final['competition enrollment minute'])
df_final['competition enrollment second'] = pd.to_numeric(df_final['competition enrollment second'])
df_final['FeatureA'] = pd.to_numeric(df_final['FeatureA'])
df_final['FeatureB'] = pd.to_numeric(df_final['FeatureB'])
df_final['FeatureF'] = pd.to_numeric(df_final['FeatureF'])
df_final['FeatureG'] = pd.to_numeric(df_final['FeatureG'])
df_final['FeatureH'] = pd.to_numeric(df_final['FeatureH'])

In [485]:
df_final['competition ended hour'] = pd.to_numeric(df_final['competition ended hour'])
df_final['competition ended minute'] = pd.to_numeric(df_final['competition ended minute'])
df_final['competition ended second'] = pd.to_numeric(df_final['competition ended second'])
df_final['competition started hour'] = pd.to_numeric(df_final['competition started hour'])
df_final['competition started minute'] = pd.to_numeric(df_final['competition started minute'])
df_final['competition started second'] = pd.to_numeric(df_final['competition started second'])
df_final['Time user completed action in hour'] = pd.to_numeric(df_final['Time user completed action in hour'])
df_final['Time user completed action in minute'] = pd.to_numeric(df_final['Time user completed action in minute'])
df_final['Time user completed action in second'] = pd.to_numeric(df_final['Time user completed action in second'])
df_final['User sign-in hour'] = pd.to_numeric(df_final['User sign-in hour'])
df_final['User sign-in minute'] = pd.to_numeric(df_final['User sign-in minute'])
df_final['User sign-in second'] = pd.to_numeric(df_final['User sign-in second'])
df_final['User sign-in month'] = pd.to_numeric(df_final['User sign-in month'])
df_final['Successful Submission Count'] = pd.to_numeric(df_final['Successful Submission Count'])

In [499]:
df_final["User sign-in month"].fillna(0, inplace = True)

In [501]:
df_final["Day last active"].fillna(0, inplace = True)

In [503]:
df_final["Time user completed action in hour"].fillna(0, inplace = True)

In [504]:
df_final["Time user completed action in minute"].fillna(0, inplace = True)

In [505]:
df_final["Time user completed action in second"].fillna(0, inplace = True)

In [486]:
df_temp1 = df_final.groupby('User_ID').max()
df_temp2 = df_final.groupby('User_ID').sum()
df_temp3 = df_final.groupby('User_ID').count() 
df_temp4 = df_final.groupby('User_ID').mean()

In [487]:
df_temp1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17391 entries, ID_000H9XOP_Month_5 to ID_ZZVUJ45W_Month_3
Data columns (total 51 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   Personal                              17391 non-null  float64
 1   Theme                                 17391 non-null  float64
 2   comment_day                           17391 non-null  float64
 3   Participant Type                      17391 non-null  float64
 4   Successful Submission Count           17391 non-null  int64  
 5   competition_enrollment_day            17391 non-null  float64
 6   FeatureA                              17391 non-null  float64
 7   FeatureB                              17391 non-null  float64
 8   FeatureC                              17391 non-null  float64
 9   FeatureD                              17391 non-null  float64
 10  FeatureE                              17391 non-null  f

In [488]:
df_final = df_temp1
df_final["User sign-in month"] = df_temp1["User sign-in month"]
df_final["count_UA"] = df_temp2["count_UA"]
df_final["Theme"] = df_temp4["Theme"]
df_final["Personal"] = df_temp4["Personal"]
df_final["Participant Type"] = df_temp4["Participant Type"]
df_final["Successful Submission Count"] = df_temp2["Successful Submission Count"]

In [489]:
df_final.reset_index(level=0, inplace=True)

In [506]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17391 entries, 0 to 17390
Data columns (total 51 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   User_ID                               17391 non-null  object 
 1   Personal                              17391 non-null  float64
 2   Theme                                 17391 non-null  float64
 3   comment_day                           17391 non-null  float64
 4   Participant Type                      17391 non-null  float64
 5   Successful Submission Count           17391 non-null  int64  
 6   competition_enrollment_day            17391 non-null  float64
 7   FeatureA                              17391 non-null  float64
 8   FeatureB                              17391 non-null  float64
 9   FeatureC                              17391 non-null  float64
 10  FeatureD                              17391 non-null  float64
 11  FeatureE       

In [507]:
df_final

User_ID  Personal  Theme  comment_day  Participant Type  \
0       ID_000H9XOP_Month_5      -1.0   -1.0          0.0               0.0   
1       ID_003YJHQA_Month_4      -1.0   -1.0          0.0               0.0   
2       ID_004UKSJV_Month_1      -1.0   -1.0          0.0               0.0   
3      ID_004UKSJV_Month_12      -1.0   -1.0          0.0               0.0   
4       ID_008D2J6C_Month_1      -1.0   -1.0          0.0               0.0   
...                     ...       ...    ...          ...               ...   
17386   ID_ZZMHNLNT_Month_4      -1.0   -1.0          0.0               0.0   
17387   ID_ZZQK0LU6_Month_3      -1.0   -1.0          0.0               1.0   
17388   ID_ZZUNZJ2U_Month_2      -1.0   -1.0          0.0               0.0   
17389   ID_ZZVM2KO7_Month_4      -1.0   -1.0          0.0               0.0   
17390   ID_ZZVUJ45W_Month_3      -1.0   -1.0          0.0               1.0   

       Successful Submission Count  competition_enrollment_day  FeatureA  \
0                                0                         0.0      -1.0   
1                                0                         0.0      -1.0   
2                                0                         0.0      -1.0   
3                                0                         0.0      -1.0   
4                                0                         0.0      -1.0   
...                            ...                         ...       ...   
17386                            0                         0.0      -1.0   
17387                            0                        29.0      -1.0   
17388                            0                         0.0      -1.0   
17389                            0                         0.0      -1.0   
17390                            0                         5.0      -1.0   

       FeatureB  FeatureC  ...  competition started hour  \
0          -1.0      -1.0  ...                        -1   
1          -1.0      -1.0  ...                        -1   
2          -1.0      -1.0  ...                        -1   
3          -1.0      -1.0  ...                        -1   
4          -1.0      -1.0  ...                        -1   
...         ...       ...  ...                       ...   
17386      -1.0      -1.0  ...                        -1   
17387      -1.0      28.0  ...                         9   
17388      -1.0      -1.0  ...                        -1   
17389      -1.0      -1.0  ...                        -1   
17390      -1.0       4.0  ...                         6   

       competition started minute  competition started second  \
0                              -1                          -1   
1                              -1                          -1   
2                              -1                          -1   
3                              -1                          -1   
4                              -1                          -1   
...                           ...                         ...   
17386                          -1                          -1   
17387                           0                           0   
17388                          -1                          -1   
17389                          -1                          -1   
17390                           0                           0   

       User sign-in hour  User sign-in minute  User sign-in second  \
0                     15                   18            11.439200   
1                     10                   30            32.261855   
2                     -1                   -1            -1.000000   
3                      8                   32            14.997443   
4                      9                   42            39.695313   
...                  ...                  ...                  ...   
17386                 10                   55            11.435972   
17387                  9                   48            48.866739   
17388                 22  

In [508]:
df_final.to_csv('Dataset.csv')